# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [61]:
import numpy as np 
import pandas as pd

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [62]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Harshit Panchal/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Harshit Panchal/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Harshit Panchal/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Harshit Panchal/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Harshit Panchal/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Harshit Panchal/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Harshit Panchal/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Harshit Panchal/an

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [63]:
np.zeros(3)

array([0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [64]:
np.size(5)

1

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [65]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x0000020A856A8B20>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [66]:
array = np.eye(10)[5 -1]
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [67]:
rrange = np.arange(10,49)
rrange

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [68]:
np.arange(10,49)[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

# 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [69]:
frange = np.arange(0,9)
frange
frange.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [70]:
arr = [1,2,0,0,4,0]
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [71]:
prr = np.eye(1)

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [72]:
err = np.random.random((3,3,3))
err

array([[[0.55160633, 0.78057845, 0.90318474],
        [0.78001186, 0.60319198, 0.62506965],
        [0.62271619, 0.37531124, 0.16096943]],

       [[0.87415598, 0.85479435, 0.86588796],
        [0.17106517, 0.96234843, 0.12579628],
        [0.43625298, 0.23333578, 0.96270343]],

       [[0.86825958, 0.6886797 , 0.57418525],
        [0.55276025, 0.90690125, 0.09626486],
        [0.35791039, 0.73717171, 0.02646956]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [73]:
trr = np.random.random(10)
trr.reshape(5,2)

array([[0.65827917, 0.47957604],
       [0.3142895 , 0.41304409],
       [0.67401751, 0.31514187],
       [0.74915465, 0.17213052],
       [0.70489684, 0.35739001]])

In [74]:
trr.max()

0.7491546535822604

In [75]:
trr.min()

0.17213051709002158

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [76]:
krr = np.random.random(30)
krr.mean()

0.5365878330021078

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [77]:
drr = np.ones((5,5))
drr[1:-1,1:-1] = 0
drr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [78]:
orr = np.ones((3,3))
orr = np.pad(orr, pad_width=1, mode='constant', constant_values=0)
orr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [79]:
0 * np.nan 

nan

In [80]:
np.nan == np.nan

False

In [81]:
np.inf > np.nan

False

In [82]:
np.nan - np.nan

nan

In [83]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [84]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [85]:
np.random.random((8,8))[::2]

array([[0.23677449, 0.50707228, 0.95612642, 0.09723293, 0.58024442,
        0.33603862, 0.9413749 , 0.67239539],
       [0.74838371, 0.22897   , 0.96496667, 0.53814294, 0.96034504,
        0.11494711, 0.57217819, 0.98545946],
       [0.35876425, 0.5355038 , 0.70035629, 0.0027881 , 0.06684569,
        0.32683183, 0.08652424, 0.84858889],
       [0.0584775 , 0.25416261, 0.87948649, 0.8767727 , 0.72500624,
        0.52979238, 0.9853569 , 0.1190307 ]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [86]:
trr = np.unravel_index(99, (6,7,8))
trr

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [87]:
wrr = np.array([[0,1], [1,0]])
z = np.tile(array,(4,4))
z

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0.]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [88]:
qrr = np.random.random((5,5))
qrrmax, qrrmin = qrr.max(), qrr.min()
Qrr = (qrr - qrr.min())/(qrr.max()-qrr.min())
Qrr

array([[0.32827627, 0.25179071, 0.        , 0.10335021, 0.23017896],
       [0.33036622, 0.27332534, 0.91848121, 0.3852525 , 0.51430811],
       [0.55306138, 0.38754892, 0.02246132, 0.20450982, 0.26177906],
       [0.78970418, 0.37675209, 0.10450895, 0.30111477, 0.56910335],
       [0.35285789, 1.        , 0.49284413, 0.61073874, 0.83112791]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [89]:
color = np.dtype([('r', np.ubyte, 1),
                  ('g', np.ubyte, 1),
                  ('b', np.ubyte, 1),
                  ('a', np.ubyte, 1)])
color

<ipython-input-89-1a5614d30f02>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([('r', np.ubyte, 1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [90]:
srr = np.dot(np.ones((5,3)), np.ones((3,2)))
srr

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [91]:
z = np.arange(11)
z 
z[(3<z) & (z <= 8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [92]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

TypeError: 'numpy.ndarray' object is not callable

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0)/np.array(0)
np.array(0)//np.array(0)
np.array([np.nan].astype(int).astype(float))

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
Z = np.arange(-10, 10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
Z = np.random.random((1,8,12))
Z1 = np.random.random((1,8,12))
np.intersect1d(Z,Z1)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64('1','D')
today = np.datetime64('today', 'D') - np.timedelta64('1','D')
tommorow = np.datetime64('today', 'D') - np.timedelta64('1','D')
yesterday
today
tommorow

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
np.arange('2016-07','2016-08', dtype = 'datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B, out =B)
np.divide(A,2, out=A)
np.negative(A, out=A)
np.divide(A,B, out=A)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
A = np.random.uniform(0, 10, 10)
A - A%1
np.floor(A)
np.ceil(A)-1


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
S = np.zeros((5,5))
S += np.arange(5)
S

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range (10):
        yield x
z = np.fromiter(generate(),dtype=float,count=-1)
z

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
X = np.linspace(0,1,11,endpoint=False)[1:]
X

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
Z = np.random.random(10)
Z.sort()
Z

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
Z = np.arange(45)
np.add.reduce(Z)

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
Q = np.random.randint(0,2,5)
R = np.random.randint(0,2,5)
np.allclose(Q,R)

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
X = np.zeros(10)
X.flags.writeable = False
X[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**0.5, Y**0.5)
Q = np.arctan2(X,Y)
print(R)
print(Q)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
Z = np.random.random(10)
Z[0] = 1

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
z = np.zeros((5,5), [('x', float), ('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
z

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.arange(8)
y = x + 0.5
c = 1.0/np.subtract.outer(x,y)
np.linalg.det(c)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=1)
Z = np.zeros((16,16))
print(Z)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x = np.arange(100)
c = np.random.uniform(0,100)
index = (np.abs(x-c)).argmin()
print(x[index])

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
z = np.zeros(10, [('position', [('x',float, 1),
                                ('y',float, 1)]),
                  ('color',    [ ('r', float, 1),
                                 ('g', float, 1),
                                 ('b', float, 1)])])
z

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
import scipy
import scipy.spatial
z = np.random.random((100,2))
d = scipy.spatial.distance.cdist(z,z)
print(d)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
z = np.arange(10, dtype=np.float32)
z = z.astype(np.int32, copy = False)
z

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
        6,  ,  , 7, 8\n
         ,  , 9,10,11\n""")
c = np.genfromtxt(s, delimiter=",", dtype=np.int)
c

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
t = np.exp(-( (d - mu)/(2.0 * sigma**2)))
print(t)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3 
z = np.zeros((n,n))
np.put(z, np.random.choice(range(n*n), p, replace=False), 1)
print(z)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x = np.random.rand(5,10)
y = x - x.mean(axis=1, keepdims=True)
y

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
e = np.random.randint(0,10,(3,3))
e[e[:,1].argsort()]
e

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
q = np.random.randint(0,3,(3,10))
~(q.any(axis=0)).any()

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
m

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
x = np.arange(3).reshape(1,3)
y = np.arange(3).reshape(3,1)
it = np.nditer([x,y,None])
for x,y,z in it: z[...] = x + y
it.operands[2]

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class arrray(np.ndarray):
    def__new__(cls,array,name='no name'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def__array__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', 'no name')
        
H = arrray(np.arange(10), 'range_10')
print(H.name)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
h = np.ones(10)
i = np.random.randint(0,len(h),20)
h += np.bincount(i, minlength=len(h))
print(h)

np.add.at(h,i,1)
print(h)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 256,256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)
I24 = np.dot(I.astype(np.uint32),[1,256,65536])
n = len(np.unique(I24))
print(n)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [93]:
d = np.random.randint(0,10,(3,4,3,4))
sum = d.sum(axis=(-2,-1))
sum

array([[36, 47, 44, 53],
       [53, 63, 46, 59],
       [55, 45, 44, 64]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [94]:
d = np.random.uniform(0,1,100)
s = np.random.randint(0,10,100)
d_sums = np.bincount(s, weights = d)
d_counts = np.bincount(s)
d_means = d_sums/d_counts
d_means

print(pd.Series(d).groupby(s).mean())

0    0.562434
1    0.526006
2    0.598189
3    0.539992
4    0.458736
5    0.292516
6    0.484058
7    0.448916
8    0.517352
9    0.404309
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [95]:
A = np.random.uniform(1,10,(4,4))
B = np.random.uniform(1,10,(4,4))

np.diag(np.dot(A,B))

array([143.76557566, 170.75732143,  92.36157364, 151.92141696])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [96]:
Q = np.array([8,9,10,11,12])
nz = 3
Q0 = np.zeros(len(Q) + (len(Q)-1)*(nz))
Q0[::nz+1] = Q
Q0

array([ 8.,  0.,  0.,  0.,  9.,  0.,  0.,  0., 10.,  0.,  0.,  0., 11.,
        0.,  0.,  0., 12.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [97]:
Q = np.ones((5,5,3))
W = 2*np.ones((5,5))
Q * W[:,:,None]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [98]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [99]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 15) ( 0, 50) ( 6, 58) ( 6, 96) ( 9, 59) ( 9, 67) (14, 49) (14, 55)
 (15, 50) (16, 18) (16, 76) (17, 75) (17, 98) (18, 76) (25, 48) (25, 93)
 (30, 62) (30, 83) (36, 39) (36, 57) (39, 57) (48, 93) (49, 55) (58, 96)
 (59, 67) (62, 83) (66, 68) (66, 80) (68, 80) (75, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [100]:
B = np.bincount([1,2,3,4,5,6,7])
V = np.repeat(np.arange(len(B)), B)
V

array([1, 2, 3, 4, 5, 6, 7])

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [101]:
def avg(a, n=3):
    hat = np.cumsum(a, dtype=float)
    hat[n:]=hat[n:] - hat[:-n]
    return hat[n-1:]/n
H = np.arange(20)
print(avg(H, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [102]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [103]:
H = np.random.randint(0,2,100)
np.logical_not(H, out=H)

H = np.random.uniform(-1.0,1.0,100)
np.negative(H, out=H)

array([ 0.6362331 , -0.03165594,  0.76365957, -0.22846293, -0.0645066 ,
       -0.37425157, -0.18988795, -0.19789276, -0.36291061, -0.62928377,
       -0.90093483, -0.27932229,  0.4745105 ,  0.46278009,  0.42936509,
        0.25307596, -0.06661512, -0.43492862,  0.63216613,  0.26080436,
       -0.01308653, -0.43391665, -0.81685468, -0.18396779, -0.98984251,
       -0.42722593,  0.15614412, -0.76085187, -0.58573552, -0.24021236,
       -0.20553069,  0.43852097, -0.54165791, -0.76732916,  0.35415125,
       -0.4750159 , -0.03381626, -0.26206107,  0.94812386,  0.32344958,
        0.47766482,  0.11396714, -0.06457258,  0.95043544, -0.1204817 ,
       -0.15829469, -0.2191175 , -0.62146783,  0.30195878, -0.3658201 ,
       -0.50008801,  0.66112919, -0.40598866,  0.08857785,  0.70267614,
        0.84110929,  0.78541439,  0.87580518, -0.33971613,  0.47053043,
       -0.50685409, -0.89983054,  0.29259589, -0.32841566,  0.75994548,
        0.52274113, -0.48739615,  0.18453032, -0.83207021, -0.27

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [104]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[11.73359564 12.76039865  4.40297082 13.96524368  4.77852328 17.93562901
  7.25648214 13.10137035  1.52885052  0.3313531 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [105]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(10,2))
np.array([distance(P0, P1, p_i) for p_i in p])

array([[8.16255250e+00, 1.65084611e+01, 1.32309786e+01, 8.52484390e+00,
        8.64966132e+00, 8.57857539e-01, 1.55151245e+01, 3.19130941e+00,
        2.70412537e+00, 1.28464408e+01],
       [7.87782684e+00, 1.84702146e+01, 1.36627716e+01, 5.82719606e+00,
        1.29279279e+01, 5.09142816e+00, 1.63182676e+01, 6.94993264e+00,
        1.09983173e+00, 1.32148060e+01],
       [3.97657857e+00, 1.12384469e+01, 8.55922599e+00, 6.98984962e+00,
        5.51737771e+00, 1.43528585e+00, 1.06406454e+01, 2.67981852e+00,
        3.33483574e+00, 8.21270187e+00],
       [1.80275236e+00, 8.78501270e+00, 6.22466627e+00, 5.87601958e+00,
        4.43923053e+00, 2.09008618e+00, 8.24784101e+00, 2.87745110e+00,
        3.19258873e+00, 5.88982149e+00],
       [7.03031432e+00, 3.43748762e+00, 3.98945845e+00, 3.86854347e+00,
        4.30344178e+00, 9.01370484e+00, 2.57698250e+00, 3.47802961e-03,
        6.35047146e+00, 4.21273660e+00],
       [1.79666258e+00, 2.76026820e+00, 1.72515722e+00, 6.22501325e+00,
   

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [144]:
H = np.random.randint(0,20,(10,10))
shape = (6,6)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Hs = np.array(list(H.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[1 0 3 2 2 6 1 8 2 7]
 [6 4 1 2 7 1 1 7 1 5]
 [9 5 6 6 1 4 7 4 8 8]
 [6 5 7 8 5 8 0 3 5 7]
 [6 4 5 7 3 0 9 1 5 7]
 [2 2 7 7 6 7 3 0 5 7]
 [0 2 1 7 1 9 8 0 3 4]
 [5 3 5 9 7 3 5 5 4 8]
 [0 1 3 1 1 6 4 5 6 6]
 [9 7 4 1 4 2 8 6 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 3 2]
 [0 0 6 4 1 2]
 [0 0 9 5 6 6]
 [0 0 6 5 7 8]]


<ipython-input-144-46ff47237fdb>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [109]:
H = np.arange(1,15,dtype=np.uint32)
Q = stride_tricks.as_strided(H,(11,4),(4,4))
Q

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [113]:
Z = np.random.uniform(0,1,(10,10))
H, D, J = np.linalg.svd(Z)

rank = np.sum(D > 1e-10)
rank



10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [115]:
H = np.random.randint(0,15,50)
np.bincount(H).argmax()

11

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [116]:
H = np.random.randint(0,5,(10,10))
n = 3

i = 1 + (H.shape[0]-3)
j = 1 + (H.shape[1]-3)
l = stride_tricks.as_strided(H, shape=(i, j, n, n), strides=H.strides + H.strides)
print(l)

[[[[0 4 2]
   [4 1 4]
   [2 3 3]]

  [[4 2 1]
   [1 4 2]
   [3 3 1]]

  [[2 1 4]
   [4 2 2]
   [3 1 0]]

  [[1 4 2]
   [2 2 4]
   [1 0 3]]

  [[4 2 4]
   [2 4 2]
   [0 3 1]]

  [[2 4 0]
   [4 2 4]
   [3 1 3]]

  [[4 0 0]
   [2 4 0]
   [1 3 1]]

  [[0 0 2]
   [4 0 4]
   [3 1 2]]]


 [[[4 1 4]
   [2 3 3]
   [0 2 1]]

  [[1 4 2]
   [3 3 1]
   [2 1 3]]

  [[4 2 2]
   [3 1 0]
   [1 3 3]]

  [[2 2 4]
   [1 0 3]
   [3 3 1]]

  [[2 4 2]
   [0 3 1]
   [3 1 4]]

  [[4 2 4]
   [3 1 3]
   [1 4 1]]

  [[2 4 0]
   [1 3 1]
   [4 1 4]]

  [[4 0 4]
   [3 1 2]
   [1 4 4]]]


 [[[2 3 3]
   [0 2 1]
   [1 3 0]]

  [[3 3 1]
   [2 1 3]
   [3 0 3]]

  [[3 1 0]
   [1 3 3]
   [0 3 1]]

  [[1 0 3]
   [3 3 1]
   [3 1 3]]

  [[0 3 1]
   [3 1 4]
   [1 3 4]]

  [[3 1 3]
   [1 4 1]
   [3 4 3]]

  [[1 3 1]
   [4 1 4]
   [4 3 2]]

  [[3 1 2]
   [1 4 4]
   [3 2 3]]]


 [[[0 2 1]
   [1 3 0]
   [3 4 4]]

  [[2 1 3]
   [3 0 3]
   [4 4 4]]

  [[1 3 3]
   [0 3 1]
   [4 4 0]]

  [[3 3 1]
   [3 1 3]
   [4 0 2]]

  [[3 1 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [117]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3 14 10  7 10]
 [14  7 15 16  7]
 [10 15  5 42  2]
 [ 7 16 42  8 13]
 [10  7  2 13  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [118]:
p, n = 10,20
H = np.ones((p,n,n))
G = np.ones((p,n,1))
B = np.tensordot(H,G, axes=[[0,2], [0,1]])
B

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [120]:
H = np.ones((16,16))
k = 4
block_sum = np.lib.stride_tricks.sliding_window_view(H, (k,k))
J = block_sum[::k, ::k, ...].sum(axis=(-2,-1))
J

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [142]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [121]:
H = np.arange(10000)
np.random.shuffle(H)
n = 5

print(H[np.argpartition(-H,n)[:n]])

[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [122]:
def vectors(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (vectors(([10, 30, 50], [9, 15], [60, 17])))

[[10  9 60]
 [10  9 17]
 [10 15 60]
 [10 15 17]
 [30  9 60]
 [30  9 17]
 [30 15 60]
 [30 15 17]
 [50  9 60]
 [50  9 17]
 [50 15 60]
 [50 15 17]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [125]:
H = np.array([('HArshit', 5.6, 6),
              ('Panchal'), 5.6, 2])
J = np.core.records.fromarrays(H.T, names='H1,H2,H3',
                              formats = 'S8, f8, i8')
J

<ipython-input-125-e401a157e41a>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  H = np.array([('HArshit', 5.6, 6),


ValueError: mismatch between the number of fields and the number of arrays

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [127]:
V = np.random.rand(int(5e7))

%timeit np.power(V,3)
%timeit V*V*V
%timeit np.einsum('i,i,i -> i',V,V,V)


2.67 s ± 108 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
716 ms ± 55 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
415 ms ± 47.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [128]:
A = np.random.randint(0,1,(8,3))
B = np.random.randint(0,1,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
rows

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [129]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 4 3]
 [3 0 2]
 [3 2 3]
 [3 3 0]
 [4 3 0]
 [4 3 0]
 [4 2 3]
 [2 3 1]
 [0 1 3]
 [0 0 4]]
[[1 4 3]
 [3 0 2]
 [3 2 3]
 [3 3 0]
 [4 3 0]
 [4 3 0]
 [4 2 3]
 [2 3 1]
 [0 1 3]
 [0 0 4]]
[[1 4 3]
 [3 0 2]
 [3 2 3]
 [3 3 0]
 [4 3 0]
 [4 3 0]
 [4 2 3]
 [2 3 1]
 [0 1 3]
 [0 0 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [132]:
H = np.array([0, 1, 30, 65, 24, 96, 105, 100], dtype=np.uint8)
np.unpackbits(H[:, np.newaxis], axis=1)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 1],
       [0, 1, 1, 0, 0, 1, 0, 0]], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [133]:
H = np.random.randint(0,5,(5,5))
uZ = np.unique(H, axis=0)
uZ

array([[0, 2, 2, 0, 0],
       [2, 1, 0, 0, 2],
       [2, 3, 1, 1, 3],
       [3, 3, 4, 2, 0],
       [4, 0, 2, 3, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [135]:
A = np.random.randint(0,5,10)
B = np.random.randint(0,5,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[ 6,  2,  0,  0,  0,  0,  2,  6,  8,  2],
       [ 9,  3,  0,  0,  0,  0,  3,  9, 12,  3],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 9,  3,  0,  0,  0,  0,  3,  9, 12,  3],
       [12,  4,  0,  0,  0,  0,  4, 12, 16,  4],
       [ 9,  3,  0,  0,  0,  0,  3,  9, 12,  3],
       [ 9,  3,  0,  0,  0,  0,  3,  9, 12,  3],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [12,  4,  0,  0,  0,  0,  4, 12, 16,  4],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [139]:
dsi = np.arange(0, 10*np.pi, 0.1)
b = 1
r = b*dsi*np.cos(dsi)
t = b*dsi*np.sin(dsi)

dr = (np.diff(r)**2 + np.diff(t)**2)**.5
z = np.zeros_like(r)
z[1:] = np.cumsum(dr)                
z_int = np.linspace(0, r.max(), 200) 
r_int = np.interp(z_int, z, r)       
t_int = np.interp(z_int, z, t)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [140]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [141]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.15070283  0.2253536 ]
